### ISSUE TITLE
This block could be extracted into a separate function

### ISSUE THREAD

**Issue by incredibleLeitman** [LauritsCSB/slot_machine_2.0#11]
https://github.com/LauritsCSB/slot_machine_2.0/blob/4e7a4e9c1381b9e02afbb2bde6d6a9aa3c952757/Program.cs#L44-L49

Also it would be nice to let the user know in case an invalid value was entered

**Comment by LauritsCSB** [comment]
This could easily be extracted into separate function, but then it would serve multiple purposes and be difficult to name.

**Comment by incredibleLeitman** [comment]
Not necessarily, if you would name it "EnsureValidPlayOption" or something like that
and the function only calls another function to retrieve that input I think this would be in order 👍 

But it is okay if you don't want to restructure this, 
I mainly created this issue because I would find it nice when you notify the user if the given input is not valid :D

**Comment by LauritsCSB** [comment]
Done and pushed. Forgot to reference the issue # in the comment though
